### PR TITLE
Add AppMessage packets

### PR DESCRIPTION
**Pull request by matejdro**
Add all packets that are necessary for implementing PebbleKit protocol.

I was unfortunately unable to test iOS side of these changes since I don't have any iOS device.

### CODE REVIEW

**Comment by ishotjr** [comment]
@matejdro I can test on iOS for you if you can provide instructions? :bowtie:

**Comment by matejdro** [comment]
We don't have an iOS app yet, so I guess the best thing you can do is run libpebblecommon tests through iOS device. I'm going to be honest here: I have no idea how this works (I have zero knowledge on Apple devices).

There is an article from april that might shed some light on this: https://medium.com/flawless-app-stories/running-kotlin-native-unit-tests-on-ios-simulator-7fd5f65305e7. Otherwise, I guess we just have to merge this and wait until iOS part of the Fossil is up and running to test it out.

**Comment by ishotjr** [comment]
@matejdro I'll take a look, but agree to maybe not hold up merge for this! :bowtie: 👍

**Comment by crc-32** [comment]
For future reference DeviceTests works with the official app dev connection for manual testing, so you could use that

**Review by crc-32 — APPROVED** [review]

**Pull request merged**
